text.copyright=o7planning.org

# ===============================
# DATABASE
# ===============================

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ann?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB